name: Playwright Tests
on: pull_request
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download baseline snapshots
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARTIFACT_NAME: baseline_${{ github.base_ref }}
        run: |
          # actions/download-artifact@v3 does not support downloading artifacts from workflow.
          # issues: https://github.com/actions/toolkit/issues/501
          # so, use gh cli.
          artifact_id=$(gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "/repos/${{ github.repository_owner}}/${{ github.repository }}/actions/artifacts?name=${{ env.ARTIFACT_NAME}}" \
          | jq -r '.artifacts[0].id')
          gh api \
          -H "Accept: application/vnd.github+json" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          "/repos/${{ github.repository }}/actions/artifacts/${artifact_id}/zip" >> baseline.zip
          unzip baseline.zip -d playwright/screenshots
          pwd
          tree ./playwright
          rm -rf baseline.zip
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
      - uses: pnpm/action-setup@v2
      - run: pnpm install
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Run Playwright tests
        run: pnpm exec playwright test
      - name: upload snapshots for prepare update baseline
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: snapshots_${{ github.event.pull_request.number }}
          path: playwright/screenshots
          retention-days: 30
      # If you want to view the report via artifact, you need to manually download the zip once and view it.
      # If you want to browse via url, you can easily browse by uploading to aws s3, gcp gcs, etc.
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
