---
name: "Upload Baseline Image"
on:
  pull_request:
    types: [closed]
  # if you need narrow paths
  # paths:
  #   - 'src/**.ts?'
permissions:
  contents: read
  actions: write

jobs:
  upload:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: ".node-version"
      - uses: pnpm/action-setup@v2
      - run: pnpm install
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Run Playwright tests
        run: pnpm exec playwright test --config ./playwright.config.ts --update-snapshots
      - name: Upload artifact for baseline
        uses: actions/upload-artifact@v2
        with:
          name: baseline_${{ github.base_ref }}
          path: playwright/screenshots
